spring.config.import=optional:file:../../.env[.properties]
spring.application.name=Hotel Management

spring.security.user.name=${SECURITY_USER:admin}
spring.security.user.password=${SECURITY_PASSWORD:admin}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hotel}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS frontend origin
frontend.url=${FRONTEND_URL:http://localhost:5173}
